spring:
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-master.yaml
  datasource:
    url: jdbc:h2:mem:testdb;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true