spring:
  session:
    store-type: jdbc
  datasource:
    url: jdbc:h2:mem:testdb;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    generate-ddl: true
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: liquibase/db.changelog-master.yaml
